language: node_js
node_js:
  - "lts/*"

stages:
  - name: build
  - name: release
    if: tag IS present

jobs:
  include:
    - stage: build
      script:
        # test that the extension builds correctly
        - npm run compile
    - stage: release
      before_install:
        - npm i -g vsce
      script:
        # fail fast
        - set -e
        # publish the extension to the Marketplace
        - vsce publish -p $VS_MARKETPLACE_TOKEN
